name: "Test Single MBPP Item Evaluation"

model:
  backend:
    - type: openai
      server_params:
        api_key: sk-b56c488f33b94df297a6314bd037b805
        base_url: https://labor-openwebui.dgx-coolify.apmic.ai/api/
      model_name: "Qwen3-30B-A3B"
evaluation:
  benchmark:
    - type: TestMBPP
      prompt_type: "Chat"
      params:
        num_samples: 1 
        temperature: 0.0
        top_p: 0.8
        max_tokens: 4096
        batch_size: 1
        num_workers: 1
        
    - type: TestMBPP
      prompt_type: "Chat"
      params:
        num_samples: 3 
        temperature: 0.0
        max_tokens: 4096
        prompt_prefix: ""
        prompt_suffix: ""
        response_prefix: ""
        response_suffix: ""
        batch_size: 1
        num_workers: 1
  
  output:
    keep_chat: false
    # path 會自動構建為 result/{model_name}/{benchmark_type}/
    # 可選：使用 experiment_name 覆蓋模型名稱