name: "Test Multi-Benchmark Evaluation"

backend:
  - type: openai
    arguments:
      api_key: sk-b56c488f33b94df297a6314bd037b805
      base_url: https://labor-openwebui.dgx-coolify.apmic.ai/api/
    model_name: "Qwen3-30B-A3B"

evaluation:
  benchmark:
    - type: LeetCode
      prompt_type: "Instruct"
      num_workers: 1
      
      num_samples: 1
      batch_size: 1
      log_batch_size: 1
      generate_args:
        temperature: 0.0
        max_tokens: 8192
        response_format:
          type: "text"
      pass_at_k: 1
    - type: BigCodeBench
      prompt_type: "Instruct"
      num_workers: 1
      num_samples: 1
      batch_size: 1
      log_batch_size: 1
      generate_args:
        temperature: 0.0
        max_tokens: 8192
        response_format:
          type: "text"
      pass_at_k: 1
    - type: BigCodeBenchHard
      prompt_type: "Instruct"
      num_workers: 1
      num_samples: 1
      batch_size: 1
      log_batch_size: 1
      generate_args:
        temperature: 0.0
        max_tokens: 8192
        response_format:
          type: "text"
      pass_at_k: 1
    - type: HumanEval
      prompt_type: "Instruct"
      num_workers: 1
      num_samples: 1
      batch_size: 1
      log_batch_size: 1
      generate_args:
        temperature: 0.0
        max_tokens: 8192
        response_format:
          type: "text"
      pass_at_k: 1
    - type: HumanEvalPlus
      prompt_type: "Instruct"
      num_workers: 1
      num_samples: 1
      batch_size: 1
      log_batch_size: 1
      generate_args:
        temperature: 0.0
        max_tokens: 8192
        response_format:
          type: "text"
      pass_at_k: 1
    - type: MBPPPlus
      prompt_type: "Instruct"
      num_workers: 1
      num_samples: 1
      batch_size: 1
      log_batch_size: 1
      generate_args:
        temperature: 0.0
        max_tokens: 8192
        response_format:
          type: "text"
      pass_at_k: 1

  output:
    keep_chat: false
    result_folder: "result/"